In [1]:
from mxnet import np, npx

## Understanding Broadcasting

In [30]:
a = np.array([[0, 1]])
b = np.array([[0],
              [1],
              [2]])
c = a+b
print(a.shape)
print(b.shape)
print(c.shape)
c

(1, 2)
(3, 1)
(3, 2)


array([[0., 1.],
       [1., 2.],
       [2., 3.]])

## Understanding Tensors

In [32]:
## Tensor : 3D - 2main_rows, 3rows, 4columns
X = np.arange(24).reshape(2, 3, 4)
X

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]])

In [33]:
# Retrieve Values
X[0]

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [34]:
X[1:,0,1]

array([13.])

## Hadamard or Element wise Product

In [36]:
a = np.arange(20).reshape(4, 5)
b = a.copy()
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [37]:
a*a

array([[  0.,   1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.,  81.],
       [100., 121., 144., 169., 196.],
       [225., 256., 289., 324., 361.]])

## Sum, Mean : Axis

* Axis : reduces dimensions
* if 0 -> squishes dimensions of rows
* if 1 -> squishes dimensions of columns

In [53]:
# axis 0 -> reduce dimension along rows
a.sum(axis = 0)

array([30., 34., 38., 42., 46.])

In [54]:
# axis 1 -> reduce dimension along columns
a.sum(axis = 1)

array([10., 35., 60., 85.])

In [51]:
a.mean(axis = 0)

array([ 7.5,  8.5,  9.5, 10.5, 11.5])

In [60]:
# Retaining Dimensions 
a.sum(axis = 1, keepdims = True)

array([[10.],
       [35.],
       [60.],
       [85.]])

In [61]:
a.sum(axis = 0, keepdims = True)

array([[30., 34., 38., 42., 46.]])

## Dot Product

In [65]:
a = np.arange(4)
b = np.arange(4)
print(a)
np.dot(a, b)

[0. 1. 2. 3.]


array(14.)

## Vector Product

* Used for enabling rotations of vectors

In [74]:
# Multiply Matrix by vector : Rotations of vector
a = np.arange(2)
b = np.arange(4).reshape(2,2)
np.dot(a, b)

array([2., 3.])

## Matrix - Matrix Product
* not to be confused with Hadamard/elem-wise product

In [77]:
a = np.ones((3, 4))
b = np.arange(8).reshape(4, 2)
np.dot(a, b)

array([[12., 16.],
       [12., 16.],
       [12., 16.]])

## Norms

* Magnitude/Size of the vector
* Norm Properties :
    * Always >= 0
    * Scale the vector -> norm is also scaled
    * Triangle Inequality 
* L1 norm less affected by outliers 
* $ Norm = (\sum |x|^p)^{\frac{1}{p}} $

In [89]:
## L2 Norm
u = np.array([3, -4])
# np.linalg.norm(u)

In [90]:
## L1 Norm
np.abs(u).sum()

array(7.)